export const CHARACTERS = [
    {
      name: "Sung Jinwoo",
      slug: "sung-jinwoo.webp",
      miniature: "sung-jinwoo.webp",
      description: 'Un cazador especial que tiene la habilidad de "subir de nivel". Solía ser un cazador de rango E apodado "el cazador más débil". Tras el incidente de la mazmorra doble, ha obtenido acceso a un "sistema" que lo ayuda a subir de nivel. A base de entrenar sin cesar, ha adquirido un poder especial que convierte a los muertos en sus "soldados sombra".',
    },
    {
      name: "Alicia Blanche",
      slug: "alicia-blanche.webp",
      miniature: "alicia-blanche.webp",
      description: 'Maestra de gremio del principal gremio de Francia, "Justitia". El público la conoce como la despiadada "bruja del hielo". Está persiguiendo al culpable del incidente de la "ruptura de raid" que está teniendo lugar por toda Europa.',
    },
    {
      name: "Amamiya Mirei",
      slug: "amamiya-mirei.webp",
      miniature: "amamiya-mirei.webp",
      description: 'Una adolescente que lucha con espada y entabla combate con el poder del alma del guerrero Oni Kuroha. Dado que trabaja como cazadora en secreto, siempre aparece en la escena llevando una máscara de Oni. Su personalidad cambia drásticamente de cuando lleva la máscara a cuando no la lleva, y a menudo siente que es dos personas diferentes.',
    },
    {
      name: "Baek Yoonho",
      slug: "baek-yoonho.webp",
      miniature: "baek-yoonho.webp",
      description: 'Maestro de gremio del gremio del Tigre Blanco y cazador de rango S. Fue uno de los cuatro miembros fundadores del gremio de la Parca. Cuando se marchó, se llevó a miembros de su anterior gremio para fundar el del Tigre Blanco. Tiene una habilidad llamada "Transformación de bestia" que le permite transformarse en una bestia mágica terrorífica.',
    },
    {
      name: "Cha Hae-In",
      slug: "cha-hae-in.webp",
      miniature: "cha-hae-in.webp",
      description: 'Es la novena cazadora de rango S de Corea del Sur y la segunda maestra de gremio del gremio de los Cazadores. Era la cazadora más fuerte de Corea del Sur hasta que Sung Jinwoo debutó. Por culpa de su habilidad especial para oler la magia, va por la vida con un pañuelo sobre la nariz. Le fascina descubrir que Sung Jinwoo es el único cazador con el que se ha topado que huele bien.',
    },
    {
      name: "Choi Jong In",
      slug: "choi-jong-in.webp",
      miniature: "choi-jong-in.webp",
      description: 'El maestro de gremio del gremio de los Cazadores, el mejor gremio de Corea del Sur. Lo han apodado "el cazador definitivo". Este cazador de tipo mago de rango S usa principalmente su magia de fuego, que puede quemar un edificio en un abrir y cerrar de ojos.',
    },
    {
      name: "Emma Laurent",
      slug: "emma-laurent.webp",
      miniature: "emma-laurent.webp",
      description: 'Una heroína bondadosa que siempre está dispuesta a ofrecerse cuando alguien necesita ayuda. Tiene una personalidad positiva y alegre, y se encarga de mantener alta la moral. Está investigando el incidente de la "ruptura de raid" con Alicia Blanche.',
    },
    {
      name: "Han Song-Yi",
      slug: "han-song-yi.webp",
      miniature: "han-song-yi.webp",
      description: 'Una adolescente que iba al mismo instituto que Sung Jinah, la hermana pequeña de Sung Jinwoo. El año que cumplió 19 años despertó como rango E. A pesar de su rango bajo y de su juventud, soñaba con convertirse en cazadora, así que se une a raids sea como sea.',
    },
    {
      name: "Hwang Dongsoo",
      slug: "hwang-dongsoo.webp",
      miniature: "hwang-dongsoo.webp",
      description: 'Octavo cazador de rango S de Corea. Dejó Corea y se unió al gremio de los Recolectores de Estados Unidos. Se enorgullece de sus poderes. Es hermano de Hwang Dongsuk, cazador de rango C.',
    },
    {
      name: "Hwang Dongsuk",
      slug: "hwang-dongsuk.webp",
      miniature: "hwang-dongsuk.webp",
      description: 'Tanque sin gremio de rango C que lidera una unidad de combate privada. Mata a gente en beneficio propio. Al fin y al cabo, "lo que pasa en las mazmorras se queda en las mazmorras".',
    },
    {
      name: "Jo Kyuhwan",
      slug: "jo-kyuhwan.webp",
      miniature: "jo-kyuhwan.webp",
      description: 'Cazador de tipo mago de rango C afiliado a la unidad de combate de Hwang Dongsuk. Se une a esa unidad de combate cuando busca "un modo seguro de ganar dinero".',
    },
    {
      name: "Kang Taeshik",
      slug: "kang-taeshik.webp",
      miniature: "kang-taeshik.webp",
      description: 'Agente de la sección de seguimiento de la Asociación de Cazadores Coreana. Siempre ocurren "accidentes" inesperados cuando lo envían a él, y los criminales a los que vigila suelen verse implicados en esos "accidentes" y morir.',
    },
    {
      name: "Kim Chul",
      slug: "kim-chul.webp",
      miniature: "kim-chul.webp",
      description: 'Tanque de rango A y estrella en alza del gremio del Tigre Blanco. Confía mucho en sus habilidades, pero es muy simple, ignorante y superficial.',
    },
    {
      name: "Kim Sangshik",
      slug: "kim-sangshik.webp",
      miniature: "kim-sangshik.webp",
      description: 'Cazador de rango D que usa su habilidad con la espada para matar bestias mágicas. Tiene la norma de priorizar la supervivencia sobre las ganancias. Valora a su familia por encima de todo y siempre pretende volver a casa al terminar el día.',
    },
    {
      name: "Lee Bora",
      slug: "lee-bora.webp",
      miniature: "lee-bora.webp",
      description: 'Una cazadora de tipo mago de rango A afiliada al gremio de los Cazadores. Posee una habilidad de invocación de nivel elevado que hace que forme parte de un grupo de élite, incluso dentro del gremio. En ocasiones se cuestiona su poder acientífico, pero está aprendiendo ese mismo poder confrontándolo directamente.',
    },
    {
      name: "Lee Joohee",
      slug: "lee-joohee.webp",
      miniature: "lee-joohee.webp",
      description: 'Sanadora de rango B muy tímida y miembro de la Asociación de Cazadores. No tenía intención de convertirse en cazadora, pero cedió ante la insistencia continua de un compañero de trabajo. Caza como voluntaria, así que solo participa en raids de dificultad baja para ayudar a los cazadores más débiles.',
    },
    {
      name: "Lim Tae Gyu",
      slug: "lim-tae-gyu.webp",
      miniature: "lim-tae-gyu.webp",
      description: 'Maestro de gremio y fundador del primer gremio de Corea, el de la Parca. Aunque este gremio gozaba de gran prestigio, su reputación se vio afectada cuando Baek Yoonho se marchó y ganó poder, momento en el que los Cazadores se hicieron cargo del mismo. Sus armas principales son las flechas mágicas, hechas de energía mágica concentrada.',
    },
    {
      name: "Meilin Fisher",
      slug: "meilin-fisher.webp",
      miniature: "meilin-fisher.webp",
      description: 'Una cazadora chinoestadounidense que despertó como rango C. Tras experimentar una situación peligrosa en una mazmorra, volvió a despertar como rango A. Un gato que en su día fue un querido miembro de su familia se le aparece como su espíritu guardián.',
    },
    {
      name: "Min Byung-Gu",
      slug: "min-byung-gu.webp",
      miniature: "min-byung-gu.webp",
      description: 'El único sanador de rango S de Corea. Se retiró por el trauma de haber presenciado la horrible muerte de sus camaradas. Sin embargo, sigue contando con habilidades de combate y de curación excepcionales que se podrían comparar con las de un cazador de rango A. De repente, ocurre algo que lo convence de volver a ser cazador.',
    },
    {
      name: "Park Heejin",
      slug: "park-heejin.webp",
      miniature: "park-heejin.webp",
      description: 'Cazadora de tipo mago del gremio del Tigre Blanco. Gracias a sus instintos de supervivencia inigualables, siempre toma la decisión que la mantendrá con vida. Tanto ella como Sung Jinwoo estuvieron implicados en el incidente del portal rojo.',
    },
    {
      name: "Song Chiyul",
      slug: "song-chiyul.webp",
      miniature: "song-chiyul.webp",
      description: 'Cazador de tipo mago de rango C. Es profesional de kendo, pero no suele usar la espada en las mazmorras debido a sus habilidades mágicas. Tras perder a su familia en un accidente provocado por un descuido de la Asociación de Cazadores, se hizo cazador voluntario y ha limpiado todas las mazmorras a las que le han enviado.',
    },
    {
      name: "Woo Jinchul",
      slug: "woo-jinchul.webp",
      miniature: "woo-jinchul.webp",
      description: 'Inspector jefe de la sección de seguimiento de la Asociación de Cazadores. Es de rango A, pero casi está al nivel de un rango S. Se unió a la Asociación de Cazadores para ser un cazador que protegiera a los cazadores. Como ayudante del presidente Go, suele cruzarse a menudo con Sung Jinwoo.',
    },
    {
      name: "Yoo Jinho",
      slug: "yoo-jinho.webp",
      miniature: "yoo-jinho.webp",
      description: 'Segundo hijo del presidente de Construcciones Yoojin, Yoo Myunghan. Jinho trabó amistad con Sung Jinwoo tras un giro del destino y varios raids. Es una de las pocas personas en las que Sung Jinwoo confía de verdad.',
    },
    {
      name: "Yoo Soohyun",
      slug: "yoo-soohyun.webp",
      miniature: "yoo-soohyun.webp",
      description: 'Cazadora de rango A y modelo famosa. No ha trabajado como cazadora desde que provocó un incidente en su primer raid, lo que le granjeó el apodo de «bomba de relojería».',
    }
];